# Generated by Django 3.2.8 on 2021-10-28 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='Issue_URL',
        ),
        migrations.AlterField(
            model_name='issues',
            name='LinkedIssue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Logic.issues'),
        ),
        migrations.CreateModel(
            name='CommentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Images', models.ImageField(upload_to='')),
                ('Reactions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('👍', '👍'), ('🚀', '🚀'), ('☀️', '☀️'), ('📣', '📣'), ('👀', '👀'), ('👍', '👍'), ('👎', '👎'), ('🥳', '🥳')], max_length=20)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='Comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Logic.commentstable'),
        ),
    ]
