# Generated by Django 3.2.8 on 2021-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Logic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="Reg_no",
            field=models.CharField(default="00VIT----", max_length=9),
        ),
    ]
