# Generated by Django 3.2.8 on 2021-10-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Logic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="Comments",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Logic.commentstable",
            ),
        ),
    ]
