# Generated by Django 3.2.8 on 2021-10-18 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Logic", "0002_alter_usermodel_reg_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="UiD",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="Reg_no",
            field=models.CharField(default="00VIT----", max_length=9, unique=True),
        ),
    ]
