# Generated by Django 3.2.8 on 2021-10-28 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0002_alter_issues_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstable',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issues',
            name='LinkedIssue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Logic.issues'),
        ),
    ]
