# Generated by Django 3.2.8 on 2021-10-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Logic", "0003_auto_20211028_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="Department",
            field=models.CharField(
                blank=True,
                choices=[("ADM", "Administrator"), ("MGM", "Management")],
                default="Admin",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="LinkedIssue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Logic.issues",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="isActive",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
