# Generated by Django 3.2.8 on 2021-10-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0004_auto_20211028_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='Comments',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Logic.commentstable'),
        ),
    ]
