# Generated by Django 3.2.8 on 2021-10-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0006_departmentfield_prioritytable_reactiontable_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentField',
        ),
        migrations.DeleteModel(
            name='PriorityTable',
        ),
        migrations.DeleteModel(
            name='ReactionTable',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
