# Generated by Django 3.2.8 on 2021-10-29 11:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0007_auto_20211029_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstable',
            name='Reactions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['👍', '👍'], ['🚀', '🚀'], ['☀️', '☀️'], ['📣', '📣'], ['👀', '👀'], ['👍', '👍'], ['👎', '👎'], ['🥳', '🥳']], max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='Issue_Tags',
            field=models.CharField(choices=[['TRI', 'Triage'], ['BUG', 'Bug'], ['DUP', 'Duplicate'], ['INP', 'In progress'], ['DEP', 'Dependencies']], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='Priority',
            field=models.CharField(choices=[['HIG', 'High'], ['MOD', 'Moderate'], ['SEV', 'Severe'], ['LOW', 'Low'], ['ML', 'Moderately Low'], ['EMER', 'Emergency']], max_length=100),
        ),
    ]
